### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by tombh** [cerrno/mueller-sph-rs#2]
Just wanted to share my appreciation. I've been playing around with SPH and Lennard-Jones in Rust and GPUs, so this repo is _exactly_ what I need at the moment 🤓

**Comment by lucas-schuermann** [comment]
Glad to hear you found it useful! I have a few other fluid simulators on GitHub as well, if you're interested in more modern techniques such as [PCISPH](https://github.com/cerrno/pcisph-rs), or [Position Based Dynamics](https://github.com/cerrno/pbd-fluid-rs).

**Comment by tombh** [comment]
Again, thank you so much. I really studied the PBD one a lot, and managed to implement a parallelised GPU version! Even the GPU code is written in Rust! On my integrated Intel GPU it manages 10k particles before showing signs of struggle. If you or anyone is interested I've made it public here https://github.com/tombh/wrach

I wasn't really sure which approach was "better", PCISPH or PBD? I just went with PBD because for whatever reason the code read easier for me. But I'm really more interested in the surface tension effects of PCISPH. Ultimately I'd love to have something for all states of matter as described here http://mmacklin.com/uppfrta_preprint.pdf

I very much don't expect you to look into it, but there's a curious problem with my parallel implementation, the water seems to "pulse". If it's not a bug (I suspect it is a bug) then my intuition is that my parallel implementation (or parallel implementations in general?) doesn't automatically lend itself to the maths of the PBD repo. Namely the step propagating the `lambda`, it's "instantaneous" in my parallel algorithm. In the serial method, the neighbouring lambdas are applied at the same time as the current particle's lambda. But this isn't possible when each particle lives in its own isolated thread and can write to the particle's properties at the same time as another thread - it's the kind of concurrency problem that could be solved by a mutex or some such, but GPU design patterns don't lend themselves to that. So instead, I save the lambda as a property and apply all the lambdas in a subsequent compute pass (the equivalent of a loop against all particles), hence the instantaneousness. So I'm wondering if this approach lacks a certain quality of "smoothing" that's found in the serial approach? Maybe the serial solver is tweaked to expect the lambdas to be applied randomly and piecemeal? Or like I say, maybe I just have a bug!

Anyway, I definitely consider it a success, and have learnt so much thanks to your repos. My current obstacle is trying to take advantage of so-called "workgroup memory", which I think could get an order of magnitude more efficiency again.

**Comment by lucas-schuermann** [comment]
Hi @tombh, apologies, I missed the notification for this comment. Great to see your progress--I've been tracking the maturation of the `wgpu` ecosystem. I have a few demos in the pipeline porting my PBD example to the GPU, as well as some more complex unified solvers with XPBD. Hopefully, one of those could serve as a reference implementation to help you debug. I'd also highly recommend Matthias Müller's [Ten Minute Physics](https://matthias-research.github.io/pages/tenMinutePhysics/index.html) series if you're interested in learning more about position-based formulations. Macklin (from the paper you linked) and Müller are frequent collaborators at Nvidia. Cheers!
